### ISSUE TITLE
Different quality scores

### ISSUE THREAD

**Issue by valeriuo** [codeinspectorio/github-action#1]
Hi!

I just integrated [my project](https://github.com/valeriuo/htslib/tree/code-inspector) with Code Inspector GitHub Action and I see a different quality score on the badge (69) than on the [dashboard](https://frontend.code-inspector.com/public/project/8649/htslib/dashboard) (81). Why the discrepancy?

![Annotation 2020-05-29 161201](https://user-images.githubusercontent.com/6553979/83275779-8d55dd80-a1c7-11ea-8c57-a78682e8e89c.png)

**Comment by juli1** [comment]
Hi @valeriuo and thanks for contacting us, we are investigating this ticket and will get back to you soon.

**Comment by juli1** [comment]
Hi @valeriuo - we investigated the issue and this was due to some violations specific to C not being ignored. We fixed the issue and the code quality score should be consistent for your project now. Thank you for your patience, please close this ticket if you believe the problem is correctly solved.

**Comment by valeriuo** [comment]
Looks good. Thanks!
