### ISSUE TITLE
Node's CommonJS script and violation

### ISSUE THREAD

**Issue by htd-tstepien** [codeinspectorio/github-action#7]
Hey, I have a small problem. Code Inspector finds my \`require\` and \`process\` functions (from Node script, written in commonJS type) as violations of non-existent functions (not declared). How can I tell Code Inspector that this is okay because this is how Node works?  
  
Besides ignoring rule `not define` - because it can ignore something important which wasn't defined

How it works right now can be seen here: https://github.com/htd-tstepien/mochawesome-json-to-md

**Comment by juli1** [comment]
Normally, the engine should recognize this is a javascript node project. We will debug it and keep you updated: having a public repository to reproduce the problem makes our life *way* easier (so, thanks a lot!) and we should be able to fix the problem within a day or two max.

**Comment by juli1** [comment]
@htd-tstepien we are deploying an update that should enable node for all check for project with commonjs. Can you please check if that works and let us know if that fixes your issue?

Thanks!

**Comment by htd-tstepien** [comment]
Hmm, it doesn't work - I mean I get the same error about violence with `process` and `require`

**Comment by juli1** [comment]
I spent some time investigating and I found the culprit! The issue is in the `.gitignore` of your repository: it ignores all `*.json` files. Our analysis engine does not use any of the files references by the `.gitignore` and `.ci-ignore` file.

Therefore, the file `package.json` is not being used to infer what framework is being used by your repository and use a "blank" configuration.

I clone your repository and removed `*.json` from `.gitignore` (see [diff here](https://github.com/juli1/mochawesome-json-to-md/commit/2cf9a3cc82f886867a7eae61bccf5f730b833229)) and it worked.

The solution might be to avoid a wildcard (you may probably want to keep `package.json` under version control) and specify files individually.

Hope that helps!

**Comment by htd-tstepien** [comment]
oh great! it helped!
